### ISSUE TITLE
Error Calidad - Opciones.

### ISSUE THREAD

**Issue by Andrga** [Proyectos1-FDI-UCM/c2223-Grupo05#11]
### Descripción
El desplegable de calidad del menú de opciones no es funcional, es decir, cuando cambio la calidad del juego, los gráficos del juego son los mismos.

### Pasos 
Entra en el menú de opciones y cambia la calidad.

### Captura de pantalla o vídeo
[![Texto alternativo](https://img.youtube.com/vi/8j0xOvKYGF4/0.jpg)](https://youtu.be/8j0xOvKYGF4)

**Comment by Mikeey84** [comment]
Es una opción que será implementada en el juego final. De momento no cambia nada.
