### ISSUE TITLE
Dash y Knock back

### ISSUE THREAD

**Issue by Andrga** [Proyectos1-FDI-UCM/c2223-Grupo05#12]
### Descripción
Cuando eres golpeado por un enemigo y este te echa hacia atrás, si haces dash en este momento, no puedes dirigirlo, sino que se va a la dirección donde te mandaba el knock back.
### Pasos 
1. Déjate golpear por un enemigo.
2. Mientras estás siendo empujado hacia atrás pulsa dash.
### Captura de pantalla o vídeo
No he podido reproducirlo para grabarlo, por lo que no parece un bug frecuente.

**Comment by MarcosPRC** [comment]
Hemos probado el error numerosas veces tanto con el enemigo de rango como con el enemigo melee y no hemos podido reproducir el error.
