### ISSUE TITLE
La UI de las vidas extra no funciona.

### ISSUE THREAD

**Issue by Andrga** [Proyectos1-FDI-UCM/c2223-Grupo05#14]
### Descripción
Las vidas extras del boss no bajan cuando el boss te golpea. Es cosa de la UI porque internamente si te está contando las vidas bien. Además, las vidas extras se conservan cuando sales del nivel del jefe. Esto pasa excepto la primera vez que entras al boss que, que entonces no te cuenta las vidas extra.
### Pasos 
1. Coge las vidas.
2. Déjate golpear.
### Captura de pantalla o vídeo
[![Texto alternativo](https://img.youtube.com/vi/-Hu60onc8k4/0.jpg)](https://youtu.be/-Hu60onc8k4)

**Comment by MarcosPRC** [comment]
Solucionado.
