### ISSUE TITLE
Error pantalla completa - Opciones.

### ISSUE THREAD

**Issue by Andrga** [Proyectos1-FDI-UCM/c2223-Grupo05#15]
### Descripción
La casilla de pantalla de “pantalla completa” no es funcional, y el espacio clickeable es mucho más pequeño de lo que debería.
### Pasos 
Entra en el menú de opciones y activa y desactiva la casilla de pantalla completa
### Captura de pantalla o vídeo
[![Texto alternativo](https://img.youtube.com/vi/atsZQg-b3W4/0.jpg)](https://youtu.be/atsZQg-b3W4)
### Sugerencia
Los botones de las opciones son bastante pequeños, creo que deberían ocupar la casilla y el texto o solo la casilla, pero no un cuadrado en el centro del texto.

**Comment by Mikeey84** [comment]
Es una opción que se implementará en el juego final. De momento no es funcional.
