### ISSUE TITLE
Parry a flechas

### ISSUE THREAD

**Issue by Andrga** [Proyectos1-FDI-UCM/c2223-Grupo05#16]
### Descripción
Si golpeas a una flecha justo antes de que esta te golpee, puedes romperla y evitar así que te golpee. (Creo que solo pasa con el enemigo que se ve en el video, no he conseguido hacerlo con ningún otro).
### Pasos 
1. Ve a una zona con enemigos a distancia.
2. Espera a que te golpee.
3. Realiza un ataque intentando romper la flecha.
### Captura de pantalla o vídeo
[![Texto alternativo](https://img.youtube.com/vi/SHxlWKuWq5k/0.jpg)](https://youtu.be/SHxlWKuWq5k)

**Comment by MarcosPRC** [comment]
Es una mecánica característica de las plumas.
