### ISSUE TITLE
Muerte lenta

### ISSUE THREAD

**Issue by Andrga** [Proyectos1-FDI-UCM/c2223-Grupo05#17]
### Descripción
Cuando te mata una flecha en el aire y pierdes tu última vida, empiezas a caer durante una cantidad de tiempo bastante grande. Además, en el video se puede ver como el juego no reacciona a ningún input.
### Pasos 
Ve a una zona con enemigos
Espera a que te golpee y pierdas todas las vidas menos una.
Pierde tu última vida en el aire.
Observa como bajas hasta el inframundo.
### Captura de pantalla o vídeo
[![Texto alternativo](https://img.youtube.com/vi/tNJumgpD56s/0.jpg)](https://youtu.be/tNJumgpD56s)

**Comment by Adriaaan63** [comment]
Corregido, hemos implementado un cronometro para que no solo reaparezca cuando toque el suelo sino que cuando pase x tiempo también pueda reaparecer.
