### ISSUE TITLE
Texto después de morir

### ISSUE THREAD

**Issue by Andrga** [Proyectos1-FDI-UCM/c2223-Grupo05#18]
### Descripción
Cuando mueres con una muerte lenta y caes a un trigger de texto, tras reaparecer sigue saliendo el texto y pudiendo moverte.
### Pasos 
1. Ve a una zona con enemigos a distancia.
2. Espera a que te golpee.
3. Observa como bajas hasta el inframundo.
### Captura de pantalla o vídeo
[![Texto alternativo](https://img.youtube.com/vi/ya7ohe47-g0/0.jpg)](https://youtu.be/ya7ohe47-g0)

**Comment by Vivu24** [comment]
Hemos cambiado el tipo de muerte, ahora se muere por cantidad de tiempo :)
