### ISSUE TITLE
Frases de personaje repetidas.

### ISSUE THREAD

**Issue by AndyMM07** [Proyectos1-FDI-UCM/c2223-Grupo05#19]
**Descripción:**

Cuando saltan nuevas líneas del personaje, aparecen las anteriores justo antes de ser reemplazadas por la nueva línea de texto. Esto hace que sea muy confuso y podamos llegar a pensar que estamos perdiendo información en el proceso.

**Pasos:**

1. Esperar a que aparezca una línea de texto nueva.
2. Observar cómo aparece un texto del anterior cuadro de texto e inmediatamente es sustituido por otro nuevo. 

**Captura de pantalla o vídeo:**

[![Texto alternativo](https://img.youtube.com/vi/ttGOWmiFJGE/0.jpg)](https://youtu.be/ttGOWmiFJGE)

**Comment by Adriaaan63** [comment]
Ya ha sido corregido el error, una vez que termina el mensaje de un diálogo se vacía el mensaje para que no salga repetido
