### ISSUE TITLE
Bug acumulación plumas infinitas y bajada de FPS - Nivel Boss

### ISSUE THREAD

**Issue by AndyMM07** [Proyectos1-FDI-UCM/c2223-Grupo05#21]
**Descripción:**

Si lanzamos plumas sobre el Boss de forma continuada, al volver al jugador, se empiezan a acumular alrededor de su cuerpo, creándose flechas infinitas. Debido a la generación infinita de flechas, el juego se enlentece, reduciendo drásticamente las imágenes por segundo (FPS).

**Pasos:**

1. Ir al selector de niveles.
2. Seleccionar el nivel del Boss.
3. Lanzar continuamente flechas contra el Boss mientras te mueves para esquivar y realizas ataques.
4. Observar cómo se ven más de tres flechas volviendo hacia el jugador y en un momento dado, las flechas se sitúan levitando alrededor del personaje produciendo la pérdida de muchos FPS.

**Captura de pantalla o vídeo:**

[![Texto alternativo](https://img.youtube.com/vi/NkahFC8k5M4/0.jpg)](https://youtu.be/NkahFC8k5M4)

**Comment by Mikeey84** [comment]
Arreglado. El problema era un cofre que causaba que las plumas tuviesen errores de comportamiento.
