### ISSUE TITLE
El personaje se convierte en un almacén de plumas.

### ISSUE THREAD

**Issue by AndyMM07** [Proyectos1-FDI-UCM/c2223-Grupo05#22]
**Descripción:**

ACLARACIÓN - EN CASO DE QUE EL ERROR "Bug acumulación plumas infinitas y bajada de FPS - Nivel Boss" NO SE PRODUZCA, PUEDE OCURRIR ESTE.
Tras lanzar muchas plumas en la fase del boss final, el jugador va recibiendo todas y cada una de ellas, convirtiéndose en un contenedor infinito de plumas. Este error también puede traer consigo la consecuencia de la reducción de imágenes por segundo, como se observa en el vídeo de prueba.

**Pasos:**

1. Ir al selector de niveles.
2. Seleccionar el nivel del Boss.
3. Lanzar continuamente plumas contra el Boss mientras te mueves para esquivar y realizas ataques.
4. Observar cómo todas las plumas van a parar al sprite del personaje colocándose tras este y reduciendo la opacidad del mismo. En un momento dado, las flechas se sitúan levitando alrededor del personaje produciendo la pérdida de muchos FPS, al igual que en el error mencionado en la "ACLARACIÓN".

**Captura de pantalla o vídeo:**

[![Texto alternativo](https://img.youtube.com/vi/OmDvlnVH_j4/0.jpg)](https://youtu.be/OmDvlnVH_j4)

**Comment by Mikeey84** [comment]
Arreglado. Había un problema con uno de los cofres que hacía que las plumas tuviesen errores en las escenas.
