### ISSUE TITLE
Si se lanzan plumas al inicio del nivel del boss, el personaje se hace invencible y no recibe daño.

### ISSUE THREAD

**Issue by AndyMM07** [Proyectos1-FDI-UCM/c2223-Grupo05#24]
**Descripción:**

Si al iniciar el nivel del boss se lanzan entre 1 y 3 flechas, el personaje se vuelve invencible a los ataques del boss.

**Pasos:**

1. Ir al selector de niveles
2. Seleccionar el nivel del boss.
3. Lanzar entre 1 y 3 flechas.
4. Dejarte golpear por el boss.
5. Observar cómo eres inmune a todo daño durante el resto del nivel.

**Captura de pantalla o vídeo:**

[![Texto alternativo](https://img.youtube.com/vi/fq61iGgZyHA/0.jpg)](https://youtu.be/fq61iGgZyHA)

**Comment by Adriaaan63** [comment]
Corregido, te trataba de un error nuestro porque no teníamos terminado del todo bien el sistema de vidas del juego
