### ISSUE TITLE
Si se lanzan plumas al principio del nivel del boss, las vidas extra no se pueden recoger.

### ISSUE THREAD

**Issue by AndyMM07** [Proyectos1-FDI-UCM/c2223-Grupo05#25]
**Descripción:**

Si al iniciar el nivel del jefe final lanzamos unas plumas y posteriormente intentamos recoger las vidas extra del nivel, estas no se sumarán al contador de vidas de la UI, aunque sí que sonará continuamente el sonido de recogida de las mismas.

**Pasos:**

1. Ir al selector de niveles.
2. Seleccionar el nivel del boss final.
3. Lanzar entre 1 y 3 plumas al comenzar el nivel.
4. Movernos a la derecha o a la izquierda hasta encontrar una plataforma con vida extra.
5. Subirse a la plataforma y pasar por encima de las vidas extra.
6. Observar cómo suena el sonido de recogida, pero no se suman al contador, ni desaparece el sprite.

**Captura de pantalla o vídeo:**

[![Texto alternativo](https://img.youtube.com/vi/wlv51t8eX5c/0.jpg)](https://youtu.be/wlv51t8eX5c)

**Comment by Adriaaan63** [comment]
Corregido, te trataba de un error nuestro porque no teníamos terminado del todo bien el sistema de vidas del juego
