### ISSUE TITLE
Error visual en el efecto parallax del nivel del boss.

### ISSUE THREAD

**Issue by AndyMM07** [Proyectos1-FDI-UCM/c2223-Grupo05#26]
**Descripción:**

En el tercer nivel (boss), si nos subimos sobre una plataforma, y saltamos, saltamos y hacemos dash o saltamos y atacamos, la cámara se desplaza hacia la izquierda y un poco hacia arriba apareciendo una sección azul plana encima de la hierba (suelo del nivel).

**Pasos:**

1. Ir al selector de niveles
2. Seleccionar el nivel del boss final.
3. Buscar una de las dos plataformas del nivel y subirse a ella.
4. Salta, salta y realiza un dash o salta y ataca.
5. Observa cómo aparece una franja plana azul sobre la hierba.

**Captura de pantalla o vídeo:**

[![Texto alternativo](https://img.youtube.com/vi/3Qur2jVVJQ8/0.jpg)](https://youtu.be/3Qur2jVVJQ8)

**Comment by Adriaaan63** [comment]
Corregido, hemos agrandado la escala del background para que no se vea el fondo azul
