### ISSUE TITLE
Bug de las plumas en los botones interactuables.

### ISSUE THREAD

**Issue by AndyMM07** [Proyectos1-FDI-UCM/c2223-Grupo05#27]
**Descripción:**

Si lanzas una pluma a un botón y luego saltas sobre dicha pluma, te sitúas sobre el sprite del botón y posteriormente intentas moverte hacia fuera, te quedas pillado dentro de los límites del sprite del botón.

**Pasos:**

1. Ir al selector de niveles.
2. Entrar en el tutorial o el nivel 1.
3. Buscar un botón interactuable.
4. Lanzar una pluma al botón.
5. Saltar sobre la pluma que has lanzado y que ha accionado el botón.
6. Colócate sobre el sprite del botón.
7. Intentar salir moviéndote a la izquierda o a la derecha pero sin saltar.

**Captura de pantalla o vídeo:**

[![Texto alternativo](https://img.youtube.com/vi/27CNPmerK00/0.jpg)](https://youtu.be/27CNPmerK00)

**Comment by MarcosPRC** [comment]
Solucionado, problema con el collider de todos los botones.
