### ISSUE TITLE
Coger la pluma del cofre.

### ISSUE THREAD

**Issue by Andrga** [Proyectos1-FDI-UCM/c2223-Grupo05#3]
### Descripción:

Cuando estás delante de un cofre y pulsas "E" para abrirlo, no puedes coger la pluma a menos que te quites de delante del cofre y te vuelvas a acercar.

### Pasos:

1. Sitúate delante de un cofre cerrado.
2. Pulsa "E" para abrirlo.
3. No puedes coger la pluma a menos que te alejes y te vuelvas a acercar.

### Video:
[![Texto alternativo](https://img.youtube.com/vi/exPU_Xc5Lf4/0.jpg)](https://youtu.be/exPU_Xc5Lf4)

### Sugerencias:
Imagino que es algo de que lo hacéis en el "OnTriggerEnter", y cuando ya estas dentro del trigger no llama al "OnTriggerEnter" si no al "OnTriggerStay" y no se puede coger.

**Comment by Mikeey84** [comment]
No es un problema como tal. Tan solo tienes que esperar a la animación para coger el pluma. No tienes que alejarte del cofre ni nada, solo esperar a que la pluma alcance el punto más alto.
