### ISSUE TITLE
Sugerencia: Tutorial de salto + dash se entiende mal

### ISSUE THREAD

**Issue by ghost** [Proyectos1-FDI-UCM/c2223-Grupo05#30]
**Descripción:**

En la parte final del tutorial se enseña el salto con dash como "space + shift". Eso da a
entender que el jugador debe pulsar space y shift al mismo tiempo.
La mecánica funciona pulsando shift una vez estás en el aire.
Sugiero cambiar el gráfico mostrado por algo que represente primero saltar, luego dash.

**Comment by MarcosPRC** [comment]
Gracias por la sugerencia, lo tendremos en cuenta.
