### ISSUE TITLE
Sugerencia: Parra pinchuda da miedo

### ISSUE THREAD

**Issue by ghost** [Proyectos1-FDI-UCM/c2223-Grupo05#32]
**Descripción:**

Sobre el segundo cofre del primer nivel se ve una parra pinchuda que hace pensar al
jugador que va a recibir daño si la toca. En cambio es únicamente de decoración.
Creo que no es intuitivo y puede ser confuso para algunos jugadores.

**Comment by Vivu24** [comment]
Lo tendremos en cuenta :)
