### ISSUE TITLE
Glitches al morir en el aire

### ISSUE THREAD

**Issue by ghost** [Proyectos1-FDI-UCM/c2223-Grupo05#33]
**Descripción:**

Cuando el jugador muere en el aire la muerte no es instantanea, sino que debe esperar a
que su cadaver caiga al suelo para reaparecer. Visualmente, si mueres al lado de una pared
iluminada, la sombra que rodea el muerto y la luz chocan y se pierde la sombra, viendose el
cuerpo del muerto.

**Pasos:**
• En el nivel tutorial, llegar al primer enemigo de rango (después de encontrar la tercera
pluma).
• Colocar plumas y saltar para colocarse justo encima del enemigo, pegado a la pared
iluminada.
• Dejarse morir por los disparos del enemigo.

Honestamente, no se si esto es un error o es era intencionado. Pensé que valía la pena mecionarlo.

**Comment by Mikeey84** [comment]
Arreglado.
Para ello hemos cambiado la evaluación de muerte y hemos añadido un contador que hace que el jugador reaparezca sin necesidad de tocar el suelo.
