### ISSUE TITLE
Movimiento en esquinas

### ISSUE THREAD

**Issue by Andrga** [Proyectos1-FDI-UCM/c2223-Grupo05#4]
### Descripción:
Cuando estás en una esquina de una plataforma el personaje se desliza hacia abajo. a veces cuando estás muy al límite y te mueves en dirección a la plataforma, el personaje se queda pillado y no se mueve.

### Pasos: 

1. Muévete hacia la esquina de una plataforma.
2. Déjate caer poco a poco, 
3. cuando estés en el límite muévete hacia la plataforma

### Video:
[![Texto alternativo](https://img.youtube.com/vi/riv1jMlolZ0/0.jpg)](https://youtu.be/riv1jMlolZ0)

### Sugerencias:
Haciendo que las esquinas de los colliders de las plataformas o del personaje no sean redondeadas se puede solucionar. Además implementar algún tipo de coyote time puede hacer más facil el plataformeo.

**Comment by AndyMM07** [comment]
Además de lo comentado por Andrés, me he fijado en que con el problema del movimiento en las esquinas, al estar aplicando un input constante de movimiento hacia una dirección, el parallax se mueve infinitamente en la dirección del input que estemos aplicando (dcha o izda):

**Vídeo:**

[![Texto alternativo](https://img.youtube.com/vi/12M4aBW2H-E/0.jpg)](https://youtu.be/12M4aBW2H-E)

**Comment by Mikeey84** [comment]
Arreglado. Hemos cambiado los colliders para que el jugador o esté arriba o se caiga.
