### ISSUE TITLE
Enemigo atascado.

### ISSUE THREAD

**Issue by Paigro** [Proyectos1-FDI-UCM/c2223-Grupo05#5]
## Descripción:
Un enemigo a melé, al activar su ataque rodado, se queda pillado en una pared justo entre una zona en la que no puede poner plumas y una en la que sí.
## Pasos:
1. En la zona vertical antes del cofre que contiene la espada pones las plumas y al hacer el último salto no subes a la plataforma.
2. El enemigo a melé rueda hacia a ti.
3. El enemigo se queda atascado en la pared.
4. Se soluciona poniéndote en el rango de visión del enemigo de nuevo.
## Vídeo:
https://youtu.be/YDsyHIFQNAw

**Comment by Adriaaan63** [comment]
Corregido, hemos ajustado mejor el collider para que no quede pillado con el tilemap
