### ISSUE TITLE
Flechas atraviesan plataformas.

### ISSUE THREAD

**Issue by Paigro** [Proyectos1-FDI-UCM/c2223-Grupo05#6]
## Descripción:
En el nivel 1, hay varios enemigos a distancia plataformas que cuando estás debajo suya, te pueden disparar.
## Pasos:
1. Entrar al nivel 1.
2. Llegar a la zona del segundo checkpoint.
3. El enemigo de esa zona de plataformas puede disparar hacia abajo atravesando la plataforma.
4. Seguir avanzando hasta la zona de plataformas después del tercer checkpoint.
5. La plataforma que activa el botón te deja debajo de un enemigo.
6. Te dispara a través de la plataforma en la que está él.
## Vídeos:
https://youtu.be/_j8RF8KMsSI
https://youtu.be/bBakPCn8A4U

**Comment by Vivu24** [comment]
Somos conscientes, tenemos algunas plataformas para que las flechas puedan traspasarla y otras para que colisionen, así podemos jugar con la dificultad de la zona variando los sitios desde las cuales te puede disparar el enemigo de rango :)
