### ISSUE TITLE
Jefe no ataca.

### ISSUE THREAD

**Issue by Paigro** [Proyectos1-FDI-UCM/c2223-Grupo05#8]
## Descripción:
Tras completar las fases del jefe y seguir haciéndole daño, este se queda quieto en el sitio en el que estaba, sin atacar ni lanzar nada, y solo girando sobre sí mismo cuando el jugador cambia de lado.
## Pasos:
1. Entrar en el nivel del jefe.
2. Atacar continuamente desbloqueando todas sus fases.
3. En un punto tras atacar, se queda quieto.
## Vídeo:
https://youtu.be/UNECVMHo4q0

**Comment by Mikeey84** [comment]
Problema solucionado.
