### ISSUE TITLE
Flechas lentas.

### ISSUE THREAD

**Issue by Paigro** [Proyectos1-FDI-UCM/c2223-Grupo05#9]
## Descripción:
A lo mejor es feature, pero algunas flechas salen lentas.
## Pasos:
Yo lo pongo por si acaso aunque a lo mejor es feature.
1. Entrar en el nivel 1.
2. Te acercas al primer enemigo con arco.
3. Al poco de que salga el láser te alejas.
4. Observar como la flecha va lenta y desaparece sin haber chocado con nada.
## Vídeo:
https://youtu.be/X40Ec4eYN8M

**Comment by MarcosPRC** [comment]
Efectivamente, es una característica implementada en la flecha.
